### ISSUE TITLE
Variables with dashes are not properly highlighted

### ISSUE THREAD

**Issue by WhyNotHugo** [mboughaba/i3config.vim#4] opened 2017-08-07 00:53 UTC
Variables with dashes are not properly highlighted, for example, in

    set $bg-color            #404552

Only `bg` is highlighted properly.

**Comment by mboughaba** [comment] 2017-10-05 16:13
Hi,
I won't be able to fix this right now :( I will have a look as soon as I get back to my i3 :100:

**Comment by WhyNotHugo** [comment] 2017-10-07 20:08
Thanks!

**Comment by mboughaba** [comment] 2018-02-15 19:35
Hi @WhyNotHugo 
I am not able to reproduce the highlighting.
I tried your example and it works fine as you can see in the screenshot below
![image](https://user-images.githubusercontent.com/3800584/36276957-bd3144e6-128f-11e8-948e-cda32a6d8292.png)

I am closing this for now. Please do not hesitate to re-open with a reproducer or some more info.

**Comment by WhyNotHugo** [comment] 2018-02-15 22:40
Actually, I just realized it's variable names with *two* dashes:

![2018-02-15t19 39 16 236204780-03 00](https://user-images.githubusercontent.com/730811/36284827-257f8556-12a1-11e8-913b-a1bada588e72.png)

**Closed as completed** 2018-02-16 06:39 UTC
Labels: bug

**Comment by mboughaba** [comment] 2018-02-16 06:43
Good find, I merge a fix for this, please check if it is working as you expected.
![image](https://user-images.githubusercontent.com/3800584/36296306-01255d92-12ed-11e8-82b1-503624e7a1ea.png)
